---
apiVersion: v1
kind: Namespace
metadata:
  name: motioneye
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: motioneye-deployment
  labels:
    app: motioneye
  namespace: motioneye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motioneye
  template:
    metadata:
      labels:
        app: motioneye
    spec:
      containers:
      - name: motioneye
        image: ccrisan/motioneye:master-armhf
        ports:
        - containerPort: 8081
        - containerPort: 8765
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: motioneye
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: motioneye
spec:
  rules:
  - http:
      paths:
      - path: /motioneye
        backend:
          serviceName: motioneye
          servicePort: 8765