---
apiVersion: v1
kind: Namespace
metadata:
  name: motioneye
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: motioneye-deployment
  labels:
    app: motioneye
  namespace: motioneye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motioneye
  template:
    metadata:
      labels:
        app: motioneye
    spec:
      containers:
      - name: motioneye
        image: ccrisan/motioneye:master-armhf
        ports:
        - containerPort: 8081
        - containerPort: 8765
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: motioneye
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: motioneye
spec:
  rules:
  - http:
      paths:
      - path: /motioneye
        backend:
          serviceName: motioneye
          servicePort: 8765
---
apiVersion: v1
kind: Service
metadata:
  name: motioneye
  namespace: motioneye
  annotations:
    metallb.universe.tf/allow-shared-ip: motioneye
spec:
  selector:
    app: motioneye
  type: LoadBalancer
  loadBalancerIP: 192.168.86.17
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: streaming
      protocol: TCP
      port: 8765
      targetPort: 8765