---
- hosts: retropie
  become: yes
  tasks:
  - name: Ensure packages are installed
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - build-essential
    - git
    - htop
    - iotop
    - libreadline-dev
    - lsb-release
    - vim

  - name: Install base system
    block:
      - name: Sudo cofiguration
        block:
          - name: keep ssh_auth_sock
            copy:
              dest: /etc/sudoers.d/keep_auth_sock
              src: "{{playbook_dir}}/../files/sudoers/keep_auth_sock"
              validate: 'visudo -cf %s'
          - name: wheel sudo group
            copy:
              dest: /etc/sudoers.d/wheel_sudo
              src: "{{playbook_dir}}/../files/sudoers/wheel_sudo"
              validate: 'visudo -cf %s'

  - name: Mount up device by label
    ansible.posix.mount:
      path: /home/pi/RetroPie/roms
      src: LABEL=roms
      fstype: ext4
      state: mounted
  
  # For some reason doesn't want to work under Ansible...
  # - name: RetroFlag safe shutdown 
  #   become: yes
  #   command: wget -O - "https://raw.githubusercontent.com/RetroFlag/retroflag-picase/master/install_gpi.sh" | sudo bash

#   - name: Check locale
#     shell: "locale | grep 'LC_ALL' | grep 'en_US'"
#     register: locale
#     ignore_errors: yes
# 
#   - name: Check if en_US.UTF-8 is installed
#     shell: "locale -a | grep 'en_US'"
#     register: locale_us
#     when: locale.rc != 0
#     ignore_errors: yes
# 
#   - name: Generate US locale
#     become: yes
#     shell: locale-gen en_US.UTF-8
#     when: locale.rc != 0 and locale_us.rc == 0
#     register: locale_us_generated
# 
#   - name: Reboot for locale install
#     become: yes
#     reboot:
#     when: locale_us_generated.rc == 0
# 
#   - name: Set locale
#     become: yes
#     shell: locale-gen en_US.UTF-8 && update-locale LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8"
#     when: locale.rc != 0 and locale_us_generated.rc == 0
#     notify: Reboot

  - name: Clone RetroPie setup
    ansible.builtin.git:
      repo: https://github.com/RetroPie/RetroPie-Setup.git
      dest: /home/pi/RetroPie-Setup
      single_branch: yes
      version: master
      depth: 1
    environment:
      GIT_TERMINAL_PROMPT: 0 # reports "terminal prompts disabled" on missing password
      # or GIT_ASKPASS: /bin/true # for git before version 2.3.0, reports "Authentication failed" on missing password

  - name: Ensure RetroPie setup script is executable
    file: 
      dest=/home/pi/RetroPie-Setup/retropie_setup.sh 
      mode=a+x

  - name: Install RetroPie
    shell: cd /home/pi/RetroPie-Setup && sudo ./retropie_packages.sh setup basic_install

  handlers:
    - name: Reboot
      ansible.builtin.reboot:
