---
- hosts: desktops
  remote_user: root
  tasks:
  - user:
      name: aur_builder
      group: wheel
  - lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'
  - name: Arch tweaks
    block:
      - name: configure parallel package compression
        lineinfile:
          path: /etc/makepkg.conf
          state: present
          line: 'COMPRESSXZ=(xz -c -z - --threads=0)'
          regexp: '^COMPRESSXZ='
      - name: set C compiler flags
        lineinfile:
          path: /etc/makepkg.conf
          state: present
          line: 'CFLAGS="-march=native -O2 -pipe -fstack-protector-strong"'
          regexp: '^CFLAGS='
      - name: set C++ compiler flags
        lineinfile:
          path: /etc/makepkg.conf
          state: present
          line: 'CXXFLAGS="${CFLAGS}"'
          regexp: '^CXXFLAGS='
      - name: set makepkg options
        lineinfile:
          path: /etc/makepkg.conf
          state: present
          line: 'OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !optipng !upx !debug)'
          regexp: '^OPTIONS='
      - name: set makepkg buildenv
        lineinfile:
          path: /etc/makepkg.conf
          state: present
          line: 'BUILDENV=(!distcc color ccache check !sign)'
          regexp: '^BUILDENV='
      - name: setup parallel make jobs
        lineinfile:
          path: /etc/makepkg.conf
          state: present
          line: 'MAKEFLAGS="-j8"'
          regexp: '^MAKEFLAGS='
      - name: ensure ccache is installed
        package:
          name: ccache
          state: present
      - name: Enable Arch multilib repo
        block:
          - lineinfile:
              path: /etc/pacman.conf
              state: present
              line: '[multilib]'
              regexp: '^#[multilib]'
          - lineinfile:
              path: /etc/pacman.conf
              state: present
              line: 'Include = /etc/pacman.d/mirrorlist'
              regexp: '^#Include = /etc/pacman.d/mirrorlist'

  - name: ensure the 'yay' aur helper is installed
    aur:
      name: yay
      skip_installed: true
      use: makepkg
    become: yes
    become_user: aur_builder
  - name: make sure that vim is installed
    package:
      name: vim
      state: present

  - name: Install base system
    block:
      - name: Sudo cofiguration
        block:
          - name: keep ssh_auth_sock
            copy:
              dest: /etc/sudoers.d/keep_auth_sock
              src: /etc/ansible/files/sudoers/keep_auth_sock
              validate: 'visudo -cf %s'
          - name: wheel sudo group
            copy:
              dest: /etc/sudoers.d/wheel_sudo
              src: /etc/ansible/files/sudoers/wheel_sudo
              validate: 'visudo -cf %s'
      - name: Install base packages
        package:
          name: "{{ item }}"
          state: present
        with_items:
          - augeas
          - bash-completion
          - docker
          - git
          - gvim
          - htop
          - linux-headers
          - moreutils
          - ncdu
          - pkgfile
          - python-pip
          - python2-pip
          - ranger
          - rsync
          - tmux
      - name: Generate initial pkgfile db
        command: /usr/bin/pkgfile -u
        args:
          creates: /var/cache/pkgfile/core.files
      - name: Create systemd-timer for updating pkfile db once per day
        block:
          - name: Create pkgfile update cron timer
            copy:
              dest: /etc/systemd/system/pkgfile_update_cron.timer
              content: |
                [Unit]
                Description=Update pkgfile db daily at 1500

                [Timer]
                OnCalendar=*:15
                Persistent=true

                [Install]
                WantedBy=timers.target
          - name: Create pkgfile update cron service
            copy:
              dest: /etc/systemd/system/pkgfile_update_cron.service
              content: |
                [Unit]
                Description=Update pkgfile daily at 1500

                [Timer]
                OnCalendar=*:15

                [Install]
                WantedBy=timers.target
      - name: Setup NTP
        block:
          - name: Set timezone
            command: timedatectl set-timezone Europe/London
            args:
              creates: /etc/localtime
            notify: reload systemd-timesyncd
          - name: NTP config
            lineinfile:
              path: /etc/systemd/timesyncd.conf
              state: present
              line: 'NTP=0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org'
              regexp: '^NTP='
            notify: reload systemd-timesyncd
          - name: NTP config fallback
            lineinfile:
              path: /etc/systemd/timesyncd.conf
              state: present
              line: 'FallbackNTP=0.pool.ntp.org 1.pool.ntp.org 0.fr.pool.ntp.org'
              regexp: '^FallbackNTP='
            notify: reload systemd-timesyncd
          - name: NTP initial sync
            shell: "if ! /usr/bin/timedatectl status | /usr/bin/grep 'NTP synchronized: yes'; then /usr/bin/timedatectl set-ntp true; fi"
      -  user:
          name: "alan"
          comment: "Alan Jenkins"
          groups: docker,sys,wheel,audio
          append: yes
      - name: Setup desktop packages
        aur:
          name: "{{ item }}"
          skip_installed: true
        with_items:
        - appimage-git
        - arandr
        - aria2
        - asciinema
        - at
        - augeas
        - awesome-terminal-fonts
        - bind-tools
        - blueman
        - bluez
        - brave-bin
        - bzip2
        - cbatticon
        - chromium
        - chromium-widevine
        - cksfv
        - clight
        # - cloud-print-connector-git
        - cmus
        - compton
        - ctags
        - deluge
        - discord
        - dmenu
        - dmidecode
        - docker-compose
        - dunst
        - dzen2
        - easytag
        - evince
        - exa
        - exfat-utils
        - feh
        - file-roller
        - firefox
        - fortune-mod
        - freemind
        - gamemode-git
        - geekbench
        - gimp
        - gitahead-bin
        - go
        - graphviz
        - handbrake
        # - howdy
        - i3-wm
        - i3blocks
        - i3blocks-contrib-git
        - i3lock
        - i3status
        - inetutils
        - inkscape
        - intel-ucode
        - iotop
        - irqbalance
        - jdk8-openjdk
        - jq
        - jupyter-notebook
        - kdenlive
        - keepassx
        - keybase-gui
        - kitty
        - lib32-gamemode-git
        - lib32-vulkan-icd-loader
        - libinput-gestures
        - libreoffice-fresh-en-gb
        - libva-intel-driver
        - lnav
        - lshw
        - lutris
        - mariadb-clients
        - mpv
        - multimc-git
        - mutt-wizard-git
        - nbtexplorer
        - ncdu
        - nemo
        - nemo-fileroller
        - nemo-image-converter
        - nemo-preview
        - nemo-python
        - nemo-seahorse
        - nemo-share
        - nemo-terminal
        - neovim
        - nethogs
        - networkmanager-openvpn
        - nmap
        - npm
        - nvidia-dkms
        - nvidia-settings
        - nvme-cli
        - obs-studio
        - openttd
        - openttd-opengfx
        - openttd-openmsx
        - openttd-opensfx
        - opus-tools
        - otf-fira-code
        - otf-font-awesome
        - ovmf
        - p7zip
        - packer
        - pass
        - pavucontrol
        - pidgin
        - pigz
        - piper
        - pitivi
        - playerctl
        - plymouth-git
        - podman
        - polybar
        - postman-bin
        - powerline-fonts
        - powershell
        - pulseaudio-modules-bt-git
        - pv
        - pwgen
        - python-pynvim
        - qemu
        - qemu-arch-extra
        - qterminal
        - reflector
        - ripgrep
        - rofi
        - samba
        - sddm
        - sddm-futuristic-theme
        - seahorse
        - shellcheck
        - slack-desktop
        - spotify
        - sshuttle
        - steam
        - steam-native-runtime
        - strace
        - stressapptest
        - swagger-codegen
        - swagger-editor-git
        - sway-git
        - swayidle-git
        - swaylock-git
        - sxiv
        - task
        - tflint
        - the_silver_searcher
        - thunar
        - thunar-archive-plugin
        - thunar-media-tags-plugin
        - thunar-volman
        - tig
        - tlp
        - tmux
        - ttf-droid
        - ttf-unifont
        - uhk-agent-appimage
        - unbound
        - unigine-heaven
        - vagrant
        - virt-manager
        - virtualbox
        - virtualbox-host-dkms
        - vlc
        - vpn-unlimited
        - vulkan-tools
        - waybar
        - wireguard-dkms
        - wireguard-tools
        - wireshark-git
        - xboxdrv
        - xclip
        - xorg-fonts-misc
        - xorg-server-xwayland
        - xorg-xev
        - xorg-xkill
        - xorg-xmodmap
        - xorg-xprop
        - xorg-xrandr
        - xorg-xrdb
        - xpadneo-dkms-git
        - xsane
        - xscreensaver
        - xsel
        - xss-lock
        - zramswap
        become: yes
        become_user: aur_builder
  - name: Enable sddm service
    service:
      name: sddm
      enabled: yes

  - name: Setup user dotfiles
    file:
      state: directory
      path: /home/alan/git
      mode: 0700
      owner: alan
      group: alan
    git:
      accept_hostkey: yes
      depth: 1
      dest: /home/alan/git/dotfiles
      repo: https://gitlab.com/alanjjenkins/dotfiles.git
    become: yes
    become_user: alan




  handlers:
    - name: reload systemd-timesyncd
      service:
        name: systemd-timesyncd
        state: restarted
