---
- hosts: desktops
  remote_user: root
  tasks:
  - user:
      name: aur_builder
      group: wheel
  - lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'
  - name: Arch tweaks
    block:
      - name: configure parallel package compression
        lineinfile:
          path: /etc/makepkg.conf
          state: present
          line: 'COMPRESSXZ=(xz -c -z - --threads=0)'
          regexp: '^COMPRESSXZ='
      - name: set C compiler flags
        lineinfile:
          path: /etc/makepkg.conf
          state: present
          line: 'CFLAGS="-march=native -O2 -pipe -fstack-protector-strong"'
          regexp: '^CFLAGS='
      - name: set C++ compiler flags
        lineinfile:
          path: /etc/makepkg.conf
          state: present
          line: 'CXXFLAGS="${CFLAGS}"'
          regexp: '^CXXFLAGS='
      - name: set makepkg options
        lineinfile:
          path: /etc/makepkg.conf
          state: present
          line: 'OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !optipng !upx !debug)'
          regexp: '^OPTIONS='
      - name: set makepkg buildenv
        lineinfile:
          path: /etc/makepkg.conf
          state: present
          line: 'BUILDENV=(!distcc color ccache check !sign)'
          regexp: '^BUILDENV='
      - name: setup parallel make jobs
        lineinfile:
          path: /etc/makepkg.conf
          state: present
          line: 'MAKEFLAGS="-j8"'
          regexp: '^MAKEFLAGS='
      - name: ensure ccache is installed
        package:
          name: ccache
          state: present

  - name: ensure the 'yay' aur helper is installed
    aur:
      name: yay
      skip_installed: true
      use: makepkg
    become: yes
    become_user: aur_builder
  - name: make sure that vim is installed
    package:
      name: vim
      state: present